# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#     container_name: frontend # Container adı təyin edirik
#     ports:
#       - "3000:8080"
#     depends_on:
#       - backend
#     networks: 
#       - my_custom_network

#   backend:
#     build:
#       context: ./backend
#     container_name: backend # Container adı təyin edirik
#     ports:
#       - "8080:8080"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_NAME=mydatabase
#       - DB_USERNAME=postgres
#       - DB_PASSWORD=postgres
#       - DB_SCHEMA=public
#     depends_on:
#       - db
#     networks:
#       - my_custom_network

#   db:
#     image: postgres:15
#     container_name: postgres-db  # Container adı təyin edirik
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - my_custom_network

# volumes:
#   pgdata:

# networks:
#   my_custom_network:






version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # AŞAĞIDAKI 'args' HİSSƏSİNİ TAMAMİLƏ SİLİN!
      # args:
      #   - VITE_APP_API_URL=http://backend:8080
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my_custom_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - my_custom_network

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_custom_network

volumes:
  pgdata:

networks:
  my_custom_network:
